# This is a basic workflow to help you get started with Actions

name: Testing labels

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: view issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "number: ${{ github.event.issue.number }}"
          echo "state: ${{ github.event.issue.state }}"
          echo "user: ${{ github.event.issue.user.login }}"
      - name: act on bug issues
        if: contains(github.event.label.name, 'bug')
        run: echo ${{ github.event.label.name }}
